### ISSUE TITLE
osr_parser.py doesn't raise ValueError if file is incorrect

### ISSUE THREAD

**Issue by Vergenter** [lenforiee/OsuPyParser#4]
The _osu_parser.py_ raises ValueError if header of file is incorrect. This behaviour should be similar for the _osr_parser.py_. it could be done by checking replay file header for `b"\x00\x80\xc3\xc9\x01\x0b"`.

**Comment by lenforiee** [comment]
This would be great idea if only replays had custom header, unfortunately the bytes you send are just mode and client version the replay was created at. Closing as I can't solve it.

**Comment by Vergenter** [comment]
Replays do not have a custom header, but it is not a problem. Bits in the file are strictly defined so it is possible to utilize that.
My current method looks like this:
```py
def is_file_replay(filepath: str) -> bool:

    with open(filepath, "rb") as f:
        file_header = f.read(5)  
        return len(file_header) == 5 and file_header.startswith(b"\x00") and file_header.endswith(b"\x01")
```
starting "\x00" is for osu gamemode and "\x01" at the last bit (little-endian) is for the year/lazer_year from version number which for lazer is 3000 and for osu is in the range of 20xx. In my lazer_db with over 20,000 replays and much more other files, no false positives.
