### ISSUE TITLE
ReplayFile should process files in similar way to OsuFile

### ISSUE THREAD

**Issue by Vergenter** [lenforiee/OsuPyParser#5]
To read file using OsuFile you need to:

1. Create instance of OsuFile
2. parse_file
```py
beatmap = osu_parser.OsuFile(full_path).parse_file()
```

To read file using ReplayFile:

1. Use factory methods _from_file_ or _from_bytes_ to get instance of ReplayFile
```py
replay= osr_parser.ReplayFile.from_file(file_path)
```
It should be unified.

**Comment by lenforiee** [comment]
resolved in c65f59e5a32c36c65d4b5d21af58e520825a7e53
